server:
  host: "0.0.0.0"
  port: "8080"

database:
  host: "localhost"
  port: "3306"
  username: "root"
  password: "lyh985211"
  database: "interview_ai"
  sslmode: "disable"

jwt:
  secret: "your-secret-key-change-this-in-production"
  expire_time: 24

llm:
  provider: "zhizengzeng"
  api_key: "sk-zk2b130c21deaf0f32023e2680aa011260769a928a495b55"
  base_url: "https://api.zhizengzeng.com/v1"
  model: "qwen-turbo"
  models:
    resume: "deepseek-v3"
    chat: "qwen-turbo"
    evaluation: "qwen-plus"
    report: "qwen-plus"

asr:
  provider: "whisper"
  api_key: "sk-zk2b130c21deaf0f32023e2680aa011260769a928a495b55"
  base_url: "https://api.zhizengzeng.com/v1"

ocr:
  tesseract_path: "D:\\resource\\tesseract\\tesseract.exe"
  pdftoppm_path: "D:\\resource\\Poppler\\poppler-25.12.0\\Library\\bin\\pdftoppm.exe"
  tessdata_path: "D:\\resource\\tesseract\\tessdata"